#!/bin/sh

# REQUIRE: dhclient

## This startup script lives in /etc/rc.d of the pxeboot image

. /etc/rc.subr

name="grpn-install"
start_cmd="${name}_start"
stop_cmd=":"

grpn-install_start()
{
  DOMAIN=$(/usr/bin/grep -h 'option domain-name ' /var/db/dhclient.leases* | /usr/bin/awk -F \" '{print $2}'| /usr/bin/head -n 1)
  HOSTNAME=$(/usr/bin/grep -h 'option host-name ' /var/db/dhclient.leases* | /usr/bin/awk -F \" '{print $2}'| /usr/bin/head -n 1)
  OS_CONFIG=$(/usr/bin/fetch -a -w 15 -q -o - http://config/host/$HOSTNAME.$DOMAIN | /usr/bin/awk '/os_config:/ {print $2}')

  /usr/bin/fetch -a -w 15 -q -o /tmp/freebsd-preinstall http://blast/profile/$OS_CONFIG-preinstall
  /bin/sh /tmp/freebsd-preinstall
  sleep 3600
}

load_rc_config $name
run_rc_command "$1"
