#!/bin/sh
# $Id$

# PROVIDE: packages
# BEFORE: LOGIN
# REQUIRE: mdinit tmp var
# KEYWORD: FreeBSD

. /etc/rc.subr

name="packages"
start_cmd="packages_start"
stop_cmd=":"

packages_start()
{
	PACKAGES=$(find /packages -type f -name *.t?z)
	if /bin/test -n "${PACKAGES}" -a -f "/usr/sbin/pkg"; then
		/usr/bin/env ASSUME_ALWAYS_YES=YES /usr/sbin/pkg bootstrap -f
		/usr/sbin/pkg -Uy install ${PACKAGES}
	fi
}

load_rc_config $name
run_rc_command "$1"
